=== UladzimirRed/Epam_Training/ThirdTask/src/main/resources/data/candies.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/candies"
        xmlns:cns="http://www.training.by/candies"
        elementFormDefault="qualified">
    <xs:element name="sweet-stuff">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="candy" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="energy" type="xs:int"></xs:element>
                            <xs:element name="ingredients">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="water" type="xs:int"></xs:element>
                                        <xs:element name="sugar" type="xs:int"></xs:element>
                                        <xs:element name="vanillin" type="xs:double"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="chocolateType" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="energyValue">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="proteins" type="xs:double"></xs:element>
                                        <xs:element name="fats" type="xs:int"></xs:element>
                                        <xs:element name="carbohydrates" type="xs:int"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="production">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="manufactor" type="xs:string"></xs:element>
                                        <xs:element name="country" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string"></xs:attribute>
                        <xs:attribute name="stuffed" type="xs:string"></xs:attribute>
                        <xs:attribute name="id" type="xs:int"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== UladzimirRed/Epam_Training/ThirdTask/src/main/resources/data/candies.xml
<?xml version="1.0" encoding="UTF-8"?>

<sweet-stuff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.train.by/candies"
             xsi:schemaLocation="http://www.train.by/candies candies.xsd">

    <candy id="a3">
        <name>Bounty</name>
        <energy>250</energy>
        <kind>
            <type>CHOCOLATE</type>
            <stuffed>true</stuffed>
        </kind>
        <ingredients>
            <water>10.0</water>
            <sugar>2.0</sugar>
            <vanillin>0.1</vanillin>
        </ingredients>
        <energyValue>
            <proteins>0.5</proteins>
            <fats>88.0</fats>
            <carbohydrates>40.0</carbohydrates>
        </energyValue>
        <production>
            <manufactor>Mars</manufactor>
            <country>United States</country>
            <foundingDate>1900-01-02</foundingDate>
        </production>
    </candy>

    <candy id="b45">
        <name>Toffifee</name>
        <energy>75</energy>
        <kind>
            <type>TOFFEE</type>
            <stuffed>false</stuffed>
        </kind>
        <ingredients>
            <water>15.0</water>
            <sugar>1.0</sugar>
            <vanillin>0.2</vanillin>
        </ingredients>
        <energyValue>
            <proteins>0.8</proteins>
            <fats>25.0</fats>
            <carbohydrates>18.0</carbohydrates>
        </energyValue>
        <production>
            <manufactor>August Storck</manufactor>
            <country>Germany</country>
            <foundingDate>1900-01-02</foundingDate>
        </production>
    </candy>

    <candy id="z33">
        <name>Fizzy Boom</name>
        <energy>15</energy>
        <kind>
            <type>CARAMEL</type>
            <stuffed>true</stuffed>
        </kind>
        <ingredients>
            <water>20.0</water>
            <sugar>25.0</sugar>
            <vanillin>0.0</vanillin>
        </ingredients>
        <energyValue>
            <proteins>1.5</proteins>
            <fats>5.0</fats>
            <carbohydrates>20.0</carbohydrates>
        </energyValue>
        <production>
            <manufactor>Roshen</manufactor>
            <country>Ukraine</country>
            <foundingDate>1900-01-02</foundingDate>
        </production>
    </candy>

</sweet-stuff>
