=== UladzimirRed/Epam_Training/ThirdTask/candies/candies.xsd
<?xml version="1.0" encoding="utf-8"?>

<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/candies"
        xmlns:cns="http://www.training.by/candies"
        elementFormDefault="qualified">
    <element name="sweet-stuff">
        <complexType>
            <sequence>
                <element maxOccurs="unbounded" name="candy">
                    <complexType>
                        <sequence>
                            <element name="name" type="xs:string" />
                            <element name="energy" type="xs:unsignedByte" />
                            <element name="ingredients">
                                <complexType>
                                    <sequence>
                                        <element name="water" type="xs:decimal" />
                                        <element name="sugar" type="xs:decimal" />
                                        <element name="vanillin" type="xs:decimal" />
                                    </sequence>
                                    <attribute name="chocolateType" type="xs:string" use="optional" />
                                </complexType>
                            </element>
                            <element name="energyValue">
                                <complexType>
                                    <sequence>
                                        <element name="proteins" type="xs:decimal" />
                                        <element name="fats" type="xs:decimal" />
                                        <element name="carbohydrates" type="xs:decimal" />
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="production">
                                <complexType>
                                    <sequence>
                                        <element name="manufactor" type="xs:string" />
                                        <element name="country" type="xs:string" />
                                    </sequence>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="candyType" type="xs:string" use="required" />
                        <attribute name="stuffed" type="xs:boolean" use="required" />
                        <attribute name="candyId" type="xs:unsignedByte" use="required" />
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== UladzimirRed/Epam_Training/ThirdTask/candies/candies.xml
<?xml version="1.0" encoding="UTF-8"?>

<sweet-stuff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.training.by/candies"
             xsi:schemaLocation="http://www.training.by/candies candies.xsd">

    <candy candyType="chocolate" stuffed="true" candyId="1">
        <name>Bounty</name>
        <energy>250</energy>
        <ingredients chocolateType="milk">
            <water>10.0</water>
            <sugar>2.0</sugar>
            <vanillin>0.1</vanillin>
        </ingredients>
        <energyValue>
            <proteins>0.5</proteins>
            <fats>88.0</fats>
            <carbohydrates>40.0</carbohydrates>
        </energyValue>
        <production>
            <manufactor>Mars</manufactor>
            <country>United States</country>
        </production>
    </candy>

    <candy candyType="toffee" stuffed="false" candyId="2">
        <name>Toffifee</name>
        <energy>75</energy>
        <ingredients>
            <water>15.0</water>
            <sugar>1.0</sugar>
            <vanillin>0.2</vanillin>
        </ingredients>
        <energyValue>
            <proteins>0.8</proteins>
            <fats>25.0</fats>
            <carbohydrates>18.0</carbohydrates>
        </energyValue>
        <production>
            <manufactor>August Storck</manufactor>
            <country>Germany</country>
        </production>
    </candy>

    <candy candyType="caramel" stuffed="true" candyId="3">
        <name>Fizzy Boom</name>
        <energy>15</energy>
        <ingredients>
            <water>20.0</water>
            <sugar>25.0</sugar>
            <vanillin>0.0</vanillin>
        </ingredients>
        <energyValue>
            <proteins>1.5</proteins>
            <fats>5.0</fats>
            <carbohydrates>20.0</carbohydrates>
        </energyValue>
        <production>
            <manufactor>Roshen</manufactor>
            <country>Ukraine</country>
        </production>
    </candy>

</sweet-stuff>
